<?
//
// $Id: f_body.phtml 85 2001-08-12 22:28:49Z kevinanlipscomb $
//
function Instance($db_link)
  {
  $the_instance = array
    (
    superapp => kix\k::EMPTY,
    be_d=> FALSE,
    photodb_prefix => kix\k::EMPTY
    );
  $db_name = $db_link->query('select database()')->fetch_row()[0];
  $be_subapp = preg_match('/^oscar|^keyclick/i',$db_name);
  $suffix = substr($db_name,-2);
  if ($suffix == '_d')
    {
    if($be_subapp) $the_instance[superapp] = 'OscarDotNet';
    $the_instance[be_d] = TRUE;
    $the_instance[photodb_prefix] = RemotePhotodbPrefix();
    }
  else if ($suffix == '_x')
    {
    if($be_subapp) $the_instance[superapp] = 'OscarTRACK_x';
    }
  else
    {
    if($be_subapp) $the_instance[superapp] = 'OscarTRACK';
    }
  return $the_instance;
  }
?>